CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name TEXT NOT NULL,
  last_name TEXT  NOT NULL,
  password TEXT NOT NULL,
  email  NOT NULL UNIQUE,
  created_at CURRENT_TIMESTAMP
)